### ISSUE TITLE
myaas docker update command fail

### ISSUE THREAD

**Issue by samuel-ye** [habitissimo/myaas#9]
when using myaas docker update command with sql dumps, it fails like below:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/code/myaas/update.py", line 114, in <module>
>     main()
>   File "/code/myaas/update.py", line 91, in main
>     db = RetryPolicy(5, delay=2)(start_db_func)
>   File "/code/myaas/utils/retry.py", line 23, in __call__
>     raise last_exception
>   File "/code/myaas/utils/retry.py", line 19, in __call__
>     return function()
>   File "/code/myaas/update.py", line 63, in start_template_database
>     db.start()
>   File "/code/myaas/backends/base.py", line 63, in start
>     subvolume = fs.find_subvolume_by_name(self.container_name)
>   File "/code/myaas/utils/btrfs.py", line 79, in find_subvolume_by_name
>     for subvolume in self.subvolumes:
>   File "/code/myaas/utils/btrfs.py", line 70, in subvolumes
>     for s in get_subvolumes(self.mountpoint)]
>   File "/code/myaas/utils/btrfs.py", line 19, in get_subvolumes
>     result = sh.btrfs.subvolume.list('-u', '-q', path)
>   File "/usr/local/lib/python3.6/site-packages/sh.py", line 1427, in __call__
>     return RunningCommand(cmd, call_args, stdin, stdout, stderr)
>   File "/usr/local/lib/python3.6/site-packages/sh.py", line 774, in __init__
>     self.wait()
>   File "/usr/local/lib/python3.6/site-packages/sh.py", line 792, in wait
>     self.handle_command_exit_code(exit_code)
>   File "/usr/local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
>     raise exc
> sh.ErrorReturnCode_1: 
> 
>   RAN: /sbin/btrfs subvolume list -u -q /myaas/data
> 
>   STDOUT:
> 
> 
>   STDERR:
> ERROR: can't perform the search -Inappropriate ioctl for device
> ERROR: can't get rootid for '/myaas/data'

The sys version is: Docker version 1.12.6, build c4618fb/1.12.6 on CentOS 7.3  3.10.0-514.26.2.el7.x86_64.

Tried with --privleged option to run docker but not work. Any ideas?

**Comment by samuel-ye** [comment]
It turns out that the docker's /myaas volume should be btrfs format and using --privileged to run the updating docker.

**Comment by hugochinchilla** [comment]
Sorry. I should update the docs, after recent changes it is expected to run
everything under privileged mode. Also it expects /myaas/data and
/myaas/dumps to be btrfs subvolumes and not regular directories.
